language: python
python:
  - "2.7"
env:
  - DJANGO_VERSION=1.6.0
# command to install dependencies
install:
  - make develop
# command to run tests
script:
  - make lint 
  - make test-python
  - make test-js
